name: IEBC Offices Data Sync with Nominatim

on:
  schedule:
    - cron: '0 6 * * 1,4'  # Run twice weekly on Monday and Thursday at 6 AM UTC
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'scripts/**'
      - '.github/workflows/iebc-sync.yml'

env:
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
  NOMINATIM_ENABLED: true

jobs:
  sync-offices-data:
    runs-on: ubuntu-latest
    timeout-minutes: 120  # Increased timeout for Nominatim rate limiting
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create data directories
      run: |
        mkdir -p data/raw data/processed data/outputs

    - name: Run data extraction pipeline with Nominatim
      run: |
        echo "Starting IEBC data pipeline with Nominatim geocoding..."
        echo "Note: This will take approximately 45-60 minutes due to Nominatim rate limits"
        python scripts/extract_pdf.py
        python scripts/clean_addresses.py
        python scripts/geocode_addresses_nominatim.py
        python scripts/csv_to_geojson.py
        python scripts/supabase_ingest.py

    - name: Commit and push generated files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/outputs/*.geojson
        git add data/processed/geocode_cache.json
        git add data/processed/geocoded_iebc_offices.csv
        git diff --staged --quiet || git commit -m "🤖 Automated IEBC offices update with Nominatim [skip ci]"
        git push
